### ISSUE TITLE
Compilation broke due to breaking changes in Azure SDK

### ISSUE THREAD

**Issue by AdallomRoy** [facebookgo/rocks-strata#32]
Hi,

I added the Azure support a couple of months back, and now their API broke and it seems to fail to compile.
I was wondering what is your approach towards vendoring packages so I could implement it to make sure we're pinned at a specific version.

Roy.

**Comment by AGFeldman** [comment]
Thanks!

You could use the vendoring support that was introduced as an experiment in go 1.5 / became official in 1.6: https://golang.org/cmd/go/#hdr-Vendor_Directories. But this project doesn't currently do any vendoring, you could use any approach that seems reasonable to you.

If the Azure changes are small, maybe let's update to the new api -- otherwise -- let's vendor.

Thanks again!

**Comment by digitalism** [comment]
I ran into the same issue and created a fork to revert 86c9a88.

See https://github.com/digitalism/rocks-strata

Now I'm able to compile this project, using

    go get github.com/digitalism/rocks-strata/strata
    cd $GOPATH/src/github.com/digitalism/rocks-strata/strata/cmd/mongo/lreplica_drivers/strata && go get -v ... && go build -v

**Comment by AdallomRoy** [comment]
Thanks for creating that alternative.
I'll really try to create a working patch this week that fixes the breaking changes on the Azure SDK side.
